//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18444.
// 
#pragma warning disable 1591

namespace GBU_Waybill_plugin.pro.mpmo.ln {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="DominoSoapBinding", Namespace="urn:DefaultNamespace")]
    public partial class MedServiceService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback dateFormatOperationCompleted;
        
        private System.Threading.SendOrPostCallback getDateSepOperationCompleted;
        
        private System.Threading.SendOrPostCallback getTimeSepOperationCompleted;
        
        private System.Threading.SendOrPostCallback getWaybillDayCountOperationCompleted;
        
        private System.Threading.SendOrPostCallback getWaybillsByTimeOperationCompleted;
        
        private System.Threading.SendOrPostCallback getEmloyeesCountOperationCompleted;
        
        private System.Threading.SendOrPostCallback getEmployeesOperationCompleted;
        
        private System.Threading.SendOrPostCallback getEmployeeByIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback getEmployeeByIndexOperationCompleted;
        
        private System.Threading.SendOrPostCallback deleteEmployeeOperationCompleted;
        
        private System.Threading.SendOrPostCallback addEmployeeOperationCompleted;
        
        private System.Threading.SendOrPostCallback updateEmployeeOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public MedServiceService(string url) {
            if (String.IsNullOrEmpty(url))
                this.Url = global::GBU_Waybill_plugin.Properties.Settings.Default.GBU_Waybill_plugin_pro_mpmo_ln_MedServiceService;
            else
                this.Url = url;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event dateFormatCompletedEventHandler dateFormatCompleted;
        
        /// <remarks/>
        public event getDateSepCompletedEventHandler getDateSepCompleted;
        
        /// <remarks/>
        public event getTimeSepCompletedEventHandler getTimeSepCompleted;
        
        /// <remarks/>
        public event getWaybillDayCountCompletedEventHandler getWaybillDayCountCompleted;
        
        /// <remarks/>
        public event getWaybillsByTimeCompletedEventHandler getWaybillsByTimeCompleted;
        
        /// <remarks/>
        public event getEmloyeesCountCompletedEventHandler getEmloyeesCountCompleted;
        
        /// <remarks/>
        public event getEmployeesCompletedEventHandler getEmployeesCompleted;
        
        /// <remarks/>
        public event getEmployeeByIdCompletedEventHandler getEmployeeByIdCompleted;
        
        /// <remarks/>
        public event getEmployeeByIndexCompletedEventHandler getEmployeeByIndexCompleted;
        
        /// <remarks/>
        public event deleteEmployeeCompletedEventHandler deleteEmployeeCompleted;
        
        /// <remarks/>
        public event addEmployeeCompletedEventHandler addEmployeeCompleted;
        
        /// <remarks/>
        public event updateEmployeeCompletedEventHandler updateEmployeeCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("dateFormat", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("dateFormatReturn", Namespace="urn:DefaultNamespace")]
        public string dateFormat() {
            object[] results = this.Invoke("dateFormat", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void dateFormatAsync() {
            this.dateFormatAsync(null);
        }
        
        /// <remarks/>
        public void dateFormatAsync(object userState) {
            if ((this.dateFormatOperationCompleted == null)) {
                this.dateFormatOperationCompleted = new System.Threading.SendOrPostCallback(this.OndateFormatOperationCompleted);
            }
            this.InvokeAsync("dateFormat", new object[0], this.dateFormatOperationCompleted, userState);
        }
        
        private void OndateFormatOperationCompleted(object arg) {
            if ((this.dateFormatCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.dateFormatCompleted(this, new dateFormatCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("getDateSep", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("getDateSepReturn", Namespace="urn:DefaultNamespace")]
        public string getDateSep() {
            object[] results = this.Invoke("getDateSep", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getDateSepAsync() {
            this.getDateSepAsync(null);
        }
        
        /// <remarks/>
        public void getDateSepAsync(object userState) {
            if ((this.getDateSepOperationCompleted == null)) {
                this.getDateSepOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetDateSepOperationCompleted);
            }
            this.InvokeAsync("getDateSep", new object[0], this.getDateSepOperationCompleted, userState);
        }
        
        private void OngetDateSepOperationCompleted(object arg) {
            if ((this.getDateSepCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getDateSepCompleted(this, new getDateSepCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("getTimeSep", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("getTimeSepReturn", Namespace="urn:DefaultNamespace")]
        public string getTimeSep() {
            object[] results = this.Invoke("getTimeSep", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getTimeSepAsync() {
            this.getTimeSepAsync(null);
        }
        
        /// <remarks/>
        public void getTimeSepAsync(object userState) {
            if ((this.getTimeSepOperationCompleted == null)) {
                this.getTimeSepOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetTimeSepOperationCompleted);
            }
            this.InvokeAsync("getTimeSep", new object[0], this.getTimeSepOperationCompleted, userState);
        }
        
        private void OngetTimeSepOperationCompleted(object arg) {
            if ((this.getTimeSepCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getTimeSepCompleted(this, new getTimeSepCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("getWaybillDayCount", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("getWaybillDayCountReturn", Namespace="urn:DefaultNamespace")]
        public int getWaybillDayCount() {
            object[] results = this.Invoke("getWaybillDayCount", new object[0]);
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void getWaybillDayCountAsync() {
            this.getWaybillDayCountAsync(null);
        }
        
        /// <remarks/>
        public void getWaybillDayCountAsync(object userState) {
            if ((this.getWaybillDayCountOperationCompleted == null)) {
                this.getWaybillDayCountOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetWaybillDayCountOperationCompleted);
            }
            this.InvokeAsync("getWaybillDayCount", new object[0], this.getWaybillDayCountOperationCompleted, userState);
        }
        
        private void OngetWaybillDayCountOperationCompleted(object arg) {
            if ((this.getWaybillDayCountCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getWaybillDayCountCompleted(this, new getWaybillDayCountCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("getWaybillsByTime", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlArrayAttribute("getWaybillsByTimeReturn", Namespace="urn:DefaultNamespace")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public Waybill[] getWaybillsByTime([System.Xml.Serialization.XmlElementAttribute(Namespace="urn:DefaultNamespace")] long unixtime) {
            object[] results = this.Invoke("getWaybillsByTime", new object[] {
                        unixtime});
            return ((Waybill[])(results[0]));
        }
        
        /// <remarks/>
        public void getWaybillsByTimeAsync(long unixtime) {
            this.getWaybillsByTimeAsync(unixtime, null);
        }
        
        /// <remarks/>
        public void getWaybillsByTimeAsync(long unixtime, object userState) {
            if ((this.getWaybillsByTimeOperationCompleted == null)) {
                this.getWaybillsByTimeOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetWaybillsByTimeOperationCompleted);
            }
            this.InvokeAsync("getWaybillsByTime", new object[] {
                        unixtime}, this.getWaybillsByTimeOperationCompleted, userState);
        }
        
        private void OngetWaybillsByTimeOperationCompleted(object arg) {
            if ((this.getWaybillsByTimeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getWaybillsByTimeCompleted(this, new getWaybillsByTimeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("getEmloyeesCount", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("getEmloyeesCountReturn", Namespace="urn:DefaultNamespace")]
        public int getEmloyeesCount() {
            object[] results = this.Invoke("getEmloyeesCount", new object[0]);
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void getEmloyeesCountAsync() {
            this.getEmloyeesCountAsync(null);
        }
        
        /// <remarks/>
        public void getEmloyeesCountAsync(object userState) {
            if ((this.getEmloyeesCountOperationCompleted == null)) {
                this.getEmloyeesCountOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetEmloyeesCountOperationCompleted);
            }
            this.InvokeAsync("getEmloyeesCount", new object[0], this.getEmloyeesCountOperationCompleted, userState);
        }
        
        private void OngetEmloyeesCountOperationCompleted(object arg) {
            if ((this.getEmloyeesCountCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getEmloyeesCountCompleted(this, new getEmloyeesCountCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("getEmployees", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlArrayAttribute("getEmployeesReturn", Namespace="urn:DefaultNamespace")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false, NestingLevel=1)]
        public object[][] getEmployees() {
            object[] results = this.Invoke("getEmployees", new object[0]);
            return ((object[][])(results[0]));
        }
        
        /// <remarks/>
        public void getEmployeesAsync() {
            this.getEmployeesAsync(null);
        }
        
        /// <remarks/>
        public void getEmployeesAsync(object userState) {
            if ((this.getEmployeesOperationCompleted == null)) {
                this.getEmployeesOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetEmployeesOperationCompleted);
            }
            this.InvokeAsync("getEmployees", new object[0], this.getEmployeesOperationCompleted, userState);
        }
        
        private void OngetEmployeesOperationCompleted(object arg) {
            if ((this.getEmployeesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getEmployeesCompleted(this, new getEmployeesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("getEmployeeById", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("getEmployeeByIdReturn", Namespace="urn:DefaultNamespace")]
        public Employee getEmployeeById([System.Xml.Serialization.XmlElementAttribute(Namespace="urn:DefaultNamespace")] string employeeId) {
            object[] results = this.Invoke("getEmployeeById", new object[] {
                        employeeId});
            return ((Employee)(results[0]));
        }
        
        /// <remarks/>
        public void getEmployeeByIdAsync(string employeeId) {
            this.getEmployeeByIdAsync(employeeId, null);
        }
        
        /// <remarks/>
        public void getEmployeeByIdAsync(string employeeId, object userState) {
            if ((this.getEmployeeByIdOperationCompleted == null)) {
                this.getEmployeeByIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetEmployeeByIdOperationCompleted);
            }
            this.InvokeAsync("getEmployeeById", new object[] {
                        employeeId}, this.getEmployeeByIdOperationCompleted, userState);
        }
        
        private void OngetEmployeeByIdOperationCompleted(object arg) {
            if ((this.getEmployeeByIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getEmployeeByIdCompleted(this, new getEmployeeByIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("getEmployeeByIndex", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("getEmployeeByIndexReturn", Namespace="urn:DefaultNamespace")]
        public Employee getEmployeeByIndex([System.Xml.Serialization.XmlElementAttribute(Namespace="urn:DefaultNamespace")] int index) {
            object[] results = this.Invoke("getEmployeeByIndex", new object[] {
                        index});
            return ((Employee)(results[0]));
        }
        
        /// <remarks/>
        public void getEmployeeByIndexAsync(int index) {
            this.getEmployeeByIndexAsync(index, null);
        }
        
        /// <remarks/>
        public void getEmployeeByIndexAsync(int index, object userState) {
            if ((this.getEmployeeByIndexOperationCompleted == null)) {
                this.getEmployeeByIndexOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetEmployeeByIndexOperationCompleted);
            }
            this.InvokeAsync("getEmployeeByIndex", new object[] {
                        index}, this.getEmployeeByIndexOperationCompleted, userState);
        }
        
        private void OngetEmployeeByIndexOperationCompleted(object arg) {
            if ((this.getEmployeeByIndexCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getEmployeeByIndexCompleted(this, new getEmployeeByIndexCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("deleteEmployee", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("deleteEmployeeReturn", Namespace="urn:DefaultNamespace")]
        public bool deleteEmployee([System.Xml.Serialization.XmlElementAttribute(Namespace="urn:DefaultNamespace")] string employeeId) {
            object[] results = this.Invoke("deleteEmployee", new object[] {
                        employeeId});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void deleteEmployeeAsync(string employeeId) {
            this.deleteEmployeeAsync(employeeId, null);
        }
        
        /// <remarks/>
        public void deleteEmployeeAsync(string employeeId, object userState) {
            if ((this.deleteEmployeeOperationCompleted == null)) {
                this.deleteEmployeeOperationCompleted = new System.Threading.SendOrPostCallback(this.OndeleteEmployeeOperationCompleted);
            }
            this.InvokeAsync("deleteEmployee", new object[] {
                        employeeId}, this.deleteEmployeeOperationCompleted, userState);
        }
        
        private void OndeleteEmployeeOperationCompleted(object arg) {
            if ((this.deleteEmployeeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.deleteEmployeeCompleted(this, new deleteEmployeeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("addEmployee", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("addEmployeeReturn", Namespace="urn:DefaultNamespace")]
        public bool addEmployee([System.Xml.Serialization.XmlElementAttribute(Namespace="urn:DefaultNamespace")] string employeeId, [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:DefaultNamespace")] string lastName, [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:DefaultNamespace")] string firstName, [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:DefaultNamespace")] string middleName, [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:DefaultNamespace", DataType="date")] System.DateTime birthday, [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:DefaultNamespace")] string department) {
            object[] results = this.Invoke("addEmployee", new object[] {
                        employeeId,
                        lastName,
                        firstName,
                        middleName,
                        birthday,
                        department});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void addEmployeeAsync(string employeeId, string lastName, string firstName, string middleName, System.DateTime birthday, string department) {
            this.addEmployeeAsync(employeeId, lastName, firstName, middleName, birthday, department, null);
        }
        
        /// <remarks/>
        public void addEmployeeAsync(string employeeId, string lastName, string firstName, string middleName, System.DateTime birthday, string department, object userState) {
            if ((this.addEmployeeOperationCompleted == null)) {
                this.addEmployeeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnaddEmployeeOperationCompleted);
            }
            this.InvokeAsync("addEmployee", new object[] {
                        employeeId,
                        lastName,
                        firstName,
                        middleName,
                        birthday,
                        department}, this.addEmployeeOperationCompleted, userState);
        }
        
        private void OnaddEmployeeOperationCompleted(object arg) {
            if ((this.addEmployeeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.addEmployeeCompleted(this, new addEmployeeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("updateEmployee", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("updateEmployeeReturn", Namespace="urn:DefaultNamespace")]
        public bool updateEmployee([System.Xml.Serialization.XmlElementAttribute(Namespace="urn:DefaultNamespace")] string employeeId, [System.Xml.Serialization.XmlArrayAttribute(Namespace="urn:DefaultNamespace")] [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)] string[] fields, [System.Xml.Serialization.XmlArrayAttribute(Namespace="urn:DefaultNamespace")] [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)] string[] values) {
            object[] results = this.Invoke("updateEmployee", new object[] {
                        employeeId,
                        fields,
                        values});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void updateEmployeeAsync(string employeeId, string[] fields, string[] values) {
            this.updateEmployeeAsync(employeeId, fields, values, null);
        }
        
        /// <remarks/>
        public void updateEmployeeAsync(string employeeId, string[] fields, string[] values, object userState) {
            if ((this.updateEmployeeOperationCompleted == null)) {
                this.updateEmployeeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnupdateEmployeeOperationCompleted);
            }
            this.InvokeAsync("updateEmployee", new object[] {
                        employeeId,
                        fields,
                        values}, this.updateEmployeeOperationCompleted, userState);
        }
        
        private void OnupdateEmployeeOperationCompleted(object arg) {
            if ((this.updateEmployeeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.updateEmployeeCompleted(this, new updateEmployeeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:DefaultNamespace")]
    public partial class Waybill {
        
        private string eDSField;
        
        private string accessField;
        
        private string beforeAfterField;
        
        private string employeeIdField;
        
        private string medicFullnameField;
        
        private long timeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string EDS {
            get {
                return this.eDSField;
            }
            set {
                this.eDSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string access {
            get {
                return this.accessField;
            }
            set {
                this.accessField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string beforeAfter {
            get {
                return this.beforeAfterField;
            }
            set {
                this.beforeAfterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string employeeId {
            get {
                return this.employeeIdField;
            }
            set {
                this.employeeIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string medicFullname {
            get {
                return this.medicFullnameField;
            }
            set {
                this.medicFullnameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long time {
            get {
                return this.timeField;
            }
            set {
                this.timeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:DefaultNamespace")]
    public partial class Employee {
        
        private System.Nullable<System.DateTime> birthdayField;
        
        private string employeeIdField;
        
        private string firstNameField;
        
        private string fullNameField;
        
        private string lastNameField;
        
        private string middleNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date", IsNullable=true)]
        public System.Nullable<System.DateTime> birthday {
            get {
                return this.birthdayField;
            }
            set {
                this.birthdayField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string employeeId {
            get {
                return this.employeeIdField;
            }
            set {
                this.employeeIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string firstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string fullName {
            get {
                return this.fullNameField;
            }
            set {
                this.fullNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string lastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string middleName {
            get {
                return this.middleNameField;
            }
            set {
                this.middleNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void dateFormatCompletedEventHandler(object sender, dateFormatCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class dateFormatCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal dateFormatCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void getDateSepCompletedEventHandler(object sender, getDateSepCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getDateSepCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getDateSepCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void getTimeSepCompletedEventHandler(object sender, getTimeSepCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getTimeSepCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getTimeSepCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void getWaybillDayCountCompletedEventHandler(object sender, getWaybillDayCountCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getWaybillDayCountCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getWaybillDayCountCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void getWaybillsByTimeCompletedEventHandler(object sender, getWaybillsByTimeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getWaybillsByTimeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getWaybillsByTimeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Waybill[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Waybill[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void getEmloyeesCountCompletedEventHandler(object sender, getEmloyeesCountCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getEmloyeesCountCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getEmloyeesCountCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void getEmployeesCompletedEventHandler(object sender, getEmployeesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getEmployeesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getEmployeesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public object[][] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object[][])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void getEmployeeByIdCompletedEventHandler(object sender, getEmployeeByIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getEmployeeByIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getEmployeeByIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Employee Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Employee)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void getEmployeeByIndexCompletedEventHandler(object sender, getEmployeeByIndexCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getEmployeeByIndexCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getEmployeeByIndexCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Employee Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Employee)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void deleteEmployeeCompletedEventHandler(object sender, deleteEmployeeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class deleteEmployeeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal deleteEmployeeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void addEmployeeCompletedEventHandler(object sender, addEmployeeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class addEmployeeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal addEmployeeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void updateEmployeeCompletedEventHandler(object sender, updateEmployeeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class updateEmployeeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal updateEmployeeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591